"""add allowed_domains to companies

Revision ID: 306508eefd22
Revises: b208ee55c7d4
Create Date: 2026-05-16 03:33:36.576675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306508eefd22'
down_revision: Union[str, Sequence[str], None] = 'b208ee55c7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('allowed_domains', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'allowed_domains')
    # ### end Alembic commands ###
